### ISSUE TITLE
Python server error

### ISSUE THREAD

**Issue by venzen** [BitMEX/api-connectors#1]
I followed the installation instructions for the Python server on Ubuntu 16.04

When I run `python3 app.py` I get the following error:

`Failed to add operation for GET /api/v1/position
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/connexion/api.py", line 237, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/usr/local/lib/python3.5/dist-packages/connexion/api.py", line 189, in add_operation
    resolver=self.resolver)
  File "/usr/local/lib/python3.5/dist-packages/connexion/operation.py", line 179, in __init__
    resolution = resolver.resolve(self)
  File "/usr/local/lib/python3.5/dist-packages/connexion/resolver.py", line 39, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/usr/local/lib/python3.5/dist-packages/connexion/resolver.py", line 65, in resolve_function_from_operation_id
    raise ResolverError(msg, sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "Position.get"!>`

Trying the server code in Ubuntu 13.10 with both Python 2 and 3 gives similar errors.

Any ideas?

**Comment by venzen** [comment]
The url being tried (*/api/v1/position*) seems to lack a domain component and is probably reverting to *localhost* but that is the point of running this server stub, right?

**Comment by STRML** [comment]
The Python `server` project is for running your own stub server that conforms to our API. Perhaps you want the client?

**Comment by ryanfox** [comment]
The python server is no longer supported. Use the [the python client](https://github.com/BitMEX/api-connectors/tree/master/official-http/python-swaggerpy) and/or [delta-server](https://github.com/BitMEX/api-connectors/tree/master/official-ws/delta-server) to interact with the API.
