### ISSUE TITLE
python swagger client

### ISSUE THREAD

**Issue by letterk** [BitMEX/api-connectors#116]
C:\Users\kisso\Anaconda3\lib\site-packages\bravado_core\spec.py:343: Warning: guid format is not registered with bravado-core!
  category=Warning,
Traceback (most recent call last):
  File "d:\_py\test.py", line 43, in <module>
    execInst="ParticipateDoNotInitiate").result()
  File "C:\Users\kisso\Anaconda3\lib\site-packages\bravado\http_future.py", line 62, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\kisso\Anaconda3\lib\site-packages\bravado\http_future.py", line 121, in result
    self.response_callbacks)
  File "C:\Users\kisso\Anaconda3\lib\site-packages\bravado\http_future.py", line 153, in unmarshal_response
    raise_on_unexpected(incoming_response)
  File "C:\Users\kisso\Anaconda3\lib\site-packages\bravado\http_future.py", line 219, in raise_on_unexpected
    raise make_http_exception(response=http_response)
bravado.exception.HTTPServiceUnavailable: 503 Service Unavailable

Return 503 errors
program crashed

**Comment by ryanfox** [comment]
What code are you running when the error occurs? Is it persistent? `503` errors correspond to the [service being overloaded.](https://testnet.bitmex.com/app/restAPI#Overload)

**Comment by letterk** [comment]
Is it persistent
after the service being overloaded  ,it should be show me the mistake and overlook this mistake,waiting for the next connection,not to stop !!!

**Comment by ryanfox** [comment]
[The documentation](https://testnet.bitmex.com/app/restAPI#Overload) specifies how clients should behave when receiving a `503` response. Closing in the absence of additional information.
