### ISSUE TITLE
Cannot read property 'XBTUSD' of undefined

### ISSUE THREAD

**Issue by gupta-apoorva** [BitMEX/api-connectors#13]
BitMEX:realtime-api { testnet: true,
  BitMEX:realtime-api   apiKeyID: '',
  BitMEX:realtime-api   apiKeySecret: '',
  BitMEX:realtime-api   endpoint: 'wss://testnet.bitmex.com/realtime' } +0ms
  BitMEX:realtime-api:socket connecting to wss://testnet.bitmex.com/realtime +4ms
BitMEX-Delta-Server listening on http://localhost:4445
TypeError: Cannot read property 'XBTUSD' of undefined
    at BitMEXClient.getData (/home/apoorv/api-connectors/official-ws/nodejs/index.js:70:38)
    at /home/apoorv/api-connectors/official-ws/delta-server/lib/server.js:70:21
    at Layer.handle [as handle_request] (/home/apoorv/api-connectors/official-ws/delta-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/apoorv/api-connectors/official-ws/delta-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/apoorv/api-connectors/official-ws/delta-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/apoorv/api-connectors/official-ws/delta-server/node_modules/express/lib/router/layer.js:95:5)
    at /home/apoorv/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:281:22
    at param (/home/apoorv/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:354:14)
    at param (/home/apoorv/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/apoorv/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:410:3)

I am getting this error while running the websocket. I am using the latest version of node and npm and followed the instructions word by word. 

Thanks

**Comment by bendelo** [comment]
Did you follow the instructions to generate an API key and put it in the config?

**Comment by bendelo** [comment]
Please paste your `config.js` (minus any API keys)

**Comment by gupta-apoorva** [comment]
I don't know what happened. I tried it again and this time it started giving the required output. Thanks BTW
