### ISSUE TITLE
Delta Server order error 

### ISSUE THREAD

**Issue by sunnyp95** [BitMEX/api-connectors#169]
I am trying to get my order information via the delta server but I keep getting the following error:
```
TypeError: Cannot read property 'XBTUSD' of undefined
    at BitMEXClient.getData (C:\Users\sunny\api-connectors\official-ws\nodejs\index.js:84:32)
    at C:\Users\sunny\api-connectors\official-ws\delta-server\lib\server.js:76:21
    at Layer.handle [as handle_request] (C:\Users\sunny\api-connectors\official-ws\delta-server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\sunny\api-connectors\official-ws\delta-server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\sunny\api-connectors\official-ws\delta-server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\sunny\api-connectors\official-ws\delta-server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\sunny\api-connectors\official-ws\delta-server\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\sunny\api-connectors\official-ws\delta-server\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\sunny\api-connectors\official-ws\delta-server\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\sunny\api-connectors\official-ws\delta-server\node_modules\express\lib\router\index.js:410:3)
```
I can connect to the delta server and get other public and private data such as 'position'. The same error also comes up for the 'execution' data.

**Comment by sunnyp95** [comment]
So the error is caused by the server sending empty arrays. There is already an issue open for this, so I am closing this.
