### ISSUE TITLE
Unexpected response code 401

### ISSUE THREAD

**Issue by yangmei090702** [BitMEX/api-connectors#181]
when I used the code apiInstance.aPIKeyEnable(apiKeyID) from /api-connectors/auto-generated/android, but got the result as below:

BasicNetwork.performRequest: Unexpected response code 401 for https://www.bitmex.com/api/v1/apiKey/enable
W/System.err: java.util.concurrent.ExecutionException: com.android.volley.AuthFailureError
W/System.err: at com.android.volley.toolbox.RequestFuture.doGet(RequestFuture.java:117)
        at com.android.volley.toolbox.RequestFuture.get(RequestFuture.java:97)
        at io.swagger.client.ApiInvoker.invokeAPI(ApiInvoker.java:377)
        at io.swagger.client.api.APIKeyApi.aPIKeyEnable(APIKeyApi.java:243)

**Comment by Feas1** [comment]
you use android to trade？

**Comment by yangmei090702** [comment]
@Feas1 i'm trying but encounter this problem. Do you have any suggestions?

**Comment by ryanfox** [comment]
BitMEX uses a custom authentication scheme described [here.](https://testnet.bitmex.com/app/apiKeysUsage)

Swagger-codegen is incompatible with this scheme, the clients in auto-generated are intended to be a starting point for further development.
