### ISSUE TITLE
not really sure whats going wrong with running the package 

### ISSUE THREAD

**Issue by ChrisJohannnesson** [BitMEX/api-connectors#186]
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\bravado\http_future.py", line 266, in unmarshal_response
    op=operation,
  File "C:\Python37\lib\site-packages\bravado\http_future.py", line 295, in unmarshal_response_inner
    response_spec = get_response_spec(status_code=response.status_code, op=op)
  File "C:\Python37\lib\site-packages\bravado_core\response.py", line 154, in get_response_spec
    "status_code or use a `default` response.".format(status_code, op))
bravado_core.exception.MatchingResponseNotFound: Response specification matching http status_code 403 not found for operation Operation(Quote_get). Either add a response specification for the status_code or use a `default` response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chris\Desktop\bitmex_testing\mex.py", line 16, in <module>
    result = client.Quote.Quote_get(symbol="XBTUSD",reverse=True,count=1).result()
  File "C:\Python37\lib\site-packages\bravado\http_future.py", line 213, in result
    swagger_result = self._get_swagger_result(incoming_response)
  File "C:\Python37\lib\site-packages\bravado\http_future.py", line 237, in _get_swagger_result
    self.request_config.response_callbacks,
  File "C:\Python37\lib\site-packages\bravado\http_future.py", line 276, in unmarshal_response
    sys.exc_info()[2])
  File "C:\Python37\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\Python37\lib\site-packages\bravado\http_future.py", line 266, in unmarshal_response
    op=operation,
  File "C:\Python37\lib\site-packages\bravado\http_future.py", line 295, in unmarshal_response_inner
    response_spec = get_response_spec(status_code=response.status_code, op=op)
  File "C:\Python37\lib\site-packages\bravado_core\response.py", line 154, in get_response_spec
    "status_code or use a `default` response.".format(status_code, op))
bravado.exception.HTTPForbidden: 403 Forbidden: Response specification matching http status_code 403 not found for operation Operation(Quote_get). Either add a response specification for the status_code or use a `default` response.

**Comment by trading8521** [comment]
> Does the error still occur? `Quote` was [disabled for a time.](https://github.com/BitMEX/api-connectors/issues/141#issuecomment-392629551)
> 
> Is the problem reproducible on other versions of python? What code are you trying to run?

Yes, I have the same issue by using result = client.Quote.Quote_get(symbol="XBTUSD", reverse=True, count=1).result()
