### ISSUE TITLE
Delta server issue

### ISSUE THREAD

**Issue by JohanRensink** [BitMEX/api-connectors#20]
I'm trying to use the delta server in light of the coming deprecation of the complete ws orderbook. I'm having some trouble though:

    /api-connectors/official-ws/delta-server# node index.js
    /root/api-connectors/official-ws/nodejs/index.js:148
        const [table, , symbol] = split;
              ^

    SyntaxError: Unexpected token [
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:374:25)
        at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/root/api-connectors/official-ws/delta-server/lib/server.js:5:22)
        at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:417:10)

Note that:

1. 'git clone git@github.com:BitMEX/api-connectors.git' from the docs didn't work for me (no permissions), I cloned using 'git clone https://github.com/BitMEX/api-connectors.git'

2. I used a package manager to install node.js using 'apt install npm' and 'apt install nodejs-legacy' (because it told me to after trying to start with 'node index.js'

Other than that I followed the documentation to the letter I believe. I can provide more context if needed.

**Comment by STRML** [comment]
Hi Johan,

That error occurs from a very old version of NodeJS.

Try installing Node 8.x from https://github.com/nodesource/distributions#installation-instructions.

**Comment by JohanRensink** [comment]
Updated to 8.5.0:

    /api-connectors/official-ws/delta-server# node -v
    v8.5.0

However:

    /api-connectors/official-ws/delta-server# node index.js
    module.js:529
        throw err;
        ^

    Error: Cannot find module 'lodash'
        at Function.Module._resolveFilename (module.js:527:15)
        at Function.Module._load (module.js:476:23)
        at Module.require (module.js:568:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/root/api-connectors/official-ws/nodejs/index.js:2:11)
        at Module._compile (module.js:624:30)
        at Object.Module._extensions..js (module.js:635:10)
        at Module.load (module.js:545:32)
        at tryModuleLoad (module.js:508:12)
        at Function.Module._load (module.js:500:3)

I've tried the solutions at [https://stackoverflow.com/a/28480226/2385490](https://stackoverflow.com/a/28480226/2385490) but they had no effect. It's fairly unclear to me where it would like to find this 'lodash' thing.

**Comment by STRML** [comment]
Ah, I suppose I should rewrite these docs from more of a beginner's view, I am assuming quite a bit of Node experience.

Type `npm install` in the delta-server's directory to install dependencies.

**Comment by JohanRensink** [comment]
You're right -> I really have no idea what I'm doing :-) thanks for being so helpful. 

I coincidentally did the `npm install` thing earlier, because it was in the documentation though. Result probably means I'm almost there though:


    /api-connectors/official-ws/delta-server# npm install
    npm WARN lifecycle bitmex-delta-server@0.2.1~postinstall: cannot run in wd %s %s (wd=%s) bitmex-
    delta-server@0.2.1 cd ../nodejs && npm install /root/api-connectors/official-ws/delta-server
    npm WARN bitmex-delta-server@0.2.1 No repository field.

    up to date in 0.539s

**Comment by STRML** [comment]
Ah, I left a step out.

Go back to `official-ws/nodejs` and type `npm install` in there as well.

**Comment by JohanRensink** [comment]
Up and running!

For future reference: This still generates some warnings for me (similar to the ones in my last post)

Thank you very much for the help.
