### ISSUE TITLE
Api authentication issue

### ISSUE THREAD

**Issue by Yackpott** [BitMEX/api-connectors#214]
with the code from github examples, I cannot get any function to work.

Traceback (most recent call last):
  File "mex.py", line 5, in <module>
    result = client.Order.Order_new(symbol='XBTUSD', orderQty=10, price=12345.0).result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bravado/http_future.py", line 213, in result
    swagger_result = self._get_swagger_result(incoming_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bravado/http_future.py", line 237, in _get_swagger_result
    self.request_config.response_callbacks,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bravado/http_future.py", line 282, in unmarshal_response
    raise_on_expected(incoming_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bravado/http_future.py", line 342, in raise_on_expected
    swagger_result=http_response.swagger_result)
bravado.exception.HTTPUnauthorized: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}

my code:

import bitmex

client = bitmex.bitmex(test=True, api_key="DELETED", api_secret="DELETED")

result = client.Order.Order_new(symbol='XBTUSD', orderQty=10, price=12345.0).result()
print(result)

**Comment by ryanfox** [comment]
1. You are connecting to testnet. Make sure you created your API key there and not on the live platform.
2. Double check your API key has the "Order" permission: https://testnet.bitmex.com/app/apiKeysUsage#API-Key-Permissions

**Comment by STRML** [comment]
Hi - please re-open if this is still an issue. Given the age and lack of follow up, I am assuming it is not.
