### ISSUE TITLE
Not Getting Executions from NodeJS Delta Server

### ISSUE THREAD

**Issue by bluworld** [BitMEX/api-connectors#217]
I can request data for instrument, orderBookL2, trade, order, position... but not for executions from the nodejs delta server. Any idea why?  I have my api id and secret configured as i can get order and position.

node config:

// Sample configuration for BitMEX-Delta-Server.
// Copy me to config.js to use custom settings.

module.exports = {
  port: 4444,

  // If false, will connect to live exchange.
  // Testnet is https://testnet.bitmex.com
//  testnet: true,
  testnet: false,

  // Symbols to watch. Add any/all symbols you are going to poll here.
  symbols: ['XBTUSD'],

  // Available streams:
  // Public:
  // ["instrument","orderBookL2","quote","trade"]
  // Private:
  // ["execution","margin","order","position"]
  streams: ["instrument","orderBookL2","trade","order","position","execution"],

  // If you want to use any of the above "private" streams, you must authenticate with an API Key.
  apiKeyID: 'ID',
  apiKeySecret: 'SECRET',

  // This prevents memory usage from getting out of control. Tweak to your needs.
  maxTableLen: 10000,
};

I run this command on another window: curl "http://localhost:4444/execution?symbol=XBTUSD"

Error message I get:

curl "http://localhost:4444/execution?symbol=XBTUSD"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;XBTUSD&#39; of undefined<br> &nbsp; &nbsp;at BitMEXClient.getData (/mnt/c/Users/.../api-connectors-master/official-ws/nodejs/index.js:84:32)<br> &nbsp; &nbsp;at /mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/lib/server.js:78:21<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/mnt/c/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at param (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/index.js:354:14)<br> &nbsp; &nbsp;at param (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/index.js:365:14)<br> &nbsp; &nbsp;at Function.process_params (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/index.js:410:3)</pre>
</body>
</html>

Error message on delta server:

TypeError: Cannot read property 'XBTUSD' of undefined
    at BitMEXClient.getData (/mnt/c/Users/... /api-connectors-master/official-ws/nodejs/index.js:84:32)
    at /mnt/c/Users/... /api-connectors-master/official-ws/delta-server-prod/lib/server.js:78:21
    at Layer.handle [as handle_request] (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/layer.js:95:5)
    at /mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/index.js:281:22
    at param (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/index.js:354:14)
    at param (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/mnt/c/Users/.../api-connectors-master/official-ws/delta-server-prod/node_modules/express/lib/router/index.js:410:3)

**Comment by alexmrs94** [comment]
I have the same problem... any ideas?

**Comment by zzm7777** [comment]
I followed the example instruction and did not modify anything. And got the same problem as blueworld.  Any suggestion?

**Comment by bluworld** [comment]
Today I'm no longer getting orderBook when subscribing to Bitmex.com, but I can get orderbook with exact same code on testnet. 

Exact same error as above.

@ryanfox is bitmex making changes to their backend code? Any ideas how to fix this. Without executions we can trade, but without orderbookL2 we are screwed.

**Comment by Elglobo** [comment]
Same problem here. Everything was okay since multiple days and Without changes I receive now

TypeError: Cannot read property 'XBTUSD' of undefined

**Comment by jvbylen** [comment]
Experiencing the same problem.
