### ISSUE TITLE
Traceback with Python

### ISSUE THREAD

**Issue by geeklingo** [BitMEX/api-connectors#227]
Trying the Bitmex api with the sample script and get the following error when i try to execute:

`# python3.7 bitmex.py
Traceback (most recent call last):
  File "bitmex.py", line 3, in <module>
    import swagger_client
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/site-packages/swagger_client-1.0.0-py3.7.egg/swagger_client/__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/site-packages/swagger_client-1.0.0-py3.7.egg/swagger_client/api/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "/usr/local/lib/python3.7/site-packages/swagger_client-1.0.0-py3.7.egg/swagger_client/api/api_key_api.py", line 127
    async=params.get('async'),
        ^
SyntaxError: invalid syntax`

`# pip3.7 -V
pip 10.0.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`

**Comment by geeklingo** [comment]
And this is all I have atm in the python script:

from __future__ import print_function
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint
