### ISSUE TITLE
401 Error with OrderNew : Testnet : JS : Seeking assistance : code+err resp included

### ISSUE THREAD

**Issue by kitt-th** [BitMEX/api-connectors#237]
Hello,

I'm experiencing an "Authorization Required" error when attempting to place an order on the testnet.
The API keys seem to be in place properly and I'm unsure why the call is being rejected. Can someone point me in the right direction?

Code and error response included below.
Thanks in advance

var BitMexApi = require('bit_mex_api');
var defaultClient = BitMexApi.ApiClient.instance;

// Configure API key authorization: apiKey
defaultClient.authentications['apiKey'] = keys['bitmexTestnetAPIKey']
defaultClient.authentications['apiSignature'] = keys['bitmexTestnetAPISecret']
defaultClient.basePath = 'https://testnet.bitmex.com/api/v1'

var apiKey = defaultClient.authentications['apiKey'];
var apiSignature = defaultClient.authentications['apiSignature'];
var apiInstance = new BitMexApi.OrderApi();
var symbol = "XBTUSD"; 

var opts = {
  'side': "Buy", 
  'simpleOrderQty': 0.2, 
  'orderQty': 8.14, 
  'price': 1.2, 
  'displayQty': 8.14,  
  'stopPx': 0.2, 
   'text': "can we see this?" // String | Optional order annotation. e.g. 'Take profit'.
};

apiInstance.orderNew(symbol, opts, callback);

==== ERROR RETURNED ====

{ Error: Unauthorized
    at Request.callback (/Users/user/node_modules/bit_mex_api/node_modules/superagent/lib/node/index.js:823:17)
    at IncomingMessage.<anonymous> (/Users/user/node_modules/bit_mex_api/node_modules/superagent/lib/node/index.js:1046:12)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  original: null,
  response: 
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res: 
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 401,
        statusMessage: 'Unauthorized',
        client: [TLSSocket],
        _consuming: true,
        _dumped: false,
        req: [ClientRequest],
        text: '{"error":{"message":"Authorization Required","name":"HTTPError"}}',
        read: [Function],
        body: [Object] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        _agent: false,
        _formData: null,
        method: 'POST',
        url: 'https://testnet.bitmex.com/api/v1/order',
        header: [Object],
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: {},
        qsRaw: [],
        _redirectList: [],
        _streamRequest: false,
        _timeout: 0,
        req: [ClientRequest],
        protocol: 'https:',
        host: 'testnet.bitmex.com',
        _callback: [Function],
        _timer: [Timeout],
        res: [IncomingMessage],
        response: [Circular],
        called: true },
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header: 'POST /api/v1/order HTTP/1.1\r\nHost: testnet.bitmex.com\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.7.1\r\nContent-Type: application/json\r\nAccept: application/json\r\nConnection: close\r\nContent-Length: 0\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/v1/order',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     links: {},
     text: '{"error":{"message":"Authorization Required","name":"HTTPError"}}',
     body: { error: [Object] },
     files: {},
     buffered: true,
     headers: 
      { date: 'Thu, 20 Sep 2018 11:55:19 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '65',
        connection: 'close',
        'set-cookie': [Array],
        'x-ratelimit-limit': '150',
        'x-ratelimit-remaining': '149',
        'x-ratelimit-reset': '1537444520',
        'x-powered-by': 'Profit',
        etag: 'W/"41-kScFg8UX9YxW6Mh8+HSZ0QlfPHk"',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        server: 'cloudflare',
        'cf-ray': '45d41a36eab91ab1-DUS' },
     header: 
      { date: 'Thu, 20 Sep 2018 11:55:19 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '65',
        connection: 'close',
        'set-cookie': [Array],
        'x-ratelimit-limit': '150',
        'x-ratelimit-remaining': '149',
        'x-ratelimit-reset': '1537444520',
        'x-powered-by': 'Profit',
        etag: 'W/"41-kScFg8UX9YxW6Mh8+HSZ0QlfPHk"',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        server: 'cloudflare',
        'cf-ray': '45d41a36eab91ab1-DUS' },
     statusCode: 401,
     status: 401,
     statusType: 4,
     info: false,
     ok: false,
     redirect: false,
     clientError: true,
     serverError: false,
     error: 
      { Error: cannot POST /api/v1/order (401)
    at Response.toError (/Users/user/node_modules/bit_mex_api/node_modules/superagent/lib/node/response.js:106:13)
    at Response.setStatusProperties (/Users/user/node_modules/bit_mex_api/node_modules/superagent/lib/node/response.js:183:12)
    at new Response (/Users/user/node_modules/bit_mex_api/node_modules/superagent/lib/node/response.js:42:8)
    at IncomingMessage.<anonymous> (/Users/user/node_modules/bit_mex_api/node_modules/superagent/lib/node/index.js:1042:22)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
        status: 401,
        text: '{"error":{"message":"Authorization Required","name":"HTTPError"}}',
        method: 'POST',
        path: '/api/v1/order' },
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: true,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     charset: 'utf-8',
     type: 'application/json',
     setEncoding: [Function: bound ],
     redirects: [] },
  status: 401 }

**Comment by kitt-th** [comment]
solved by ignoring require('bit_mex_api') & coding the REST POST using this example: https://github.com/BitMEX/api-connectors/blob/master/official-http/node-request/index.js
