### ISSUE TITLE
Websocket Authentification fails on bitmex/realtime. But success on Testnet. Different Protocol?

### ISSUE THREAD

**Issue by se-l** [BitMEX/api-connectors#249]
Hi - I successfully connect to wss://testnet.bitmex/realtime but fail on wss://bitmex/realtime. Error:

 An error has occurred during a TLS handshake. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at WebSocketSharp.WebSocket.setClientStream()
   --- End of inner exception stack trace ---
   at WebSocketSharp.WebSocket.setClientStream()
   at WebSocketSharp.WebSocket.doHandshake()
   at WebSocketSharp.WebSocket.connect()

Tried As suggested [here](https://github.com/sta/websocket-sharp/issues/356) I specified the TLS protocol version by: 
_websocketsharpinstance.SslConfiguration.EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls12;

For Default above error, For Tls12 and Tls 11, the websocket instance returns 'Indicating the redirection' before hitting timeout

Any ideas??? Or in what way the testnet and 'main'net websockets are different... Thanks
Using .NET 4.5.2

**Comment by se-l** [comment]
wrong url:    WWW.bitmex.com/realtime
