### ISSUE TITLE
I can't "import bitmex"... error message

### ISSUE THREAD

**Issue by nicix21** [BitMEX/api-connectors#267]
Hello I'm quite newbie. 
I installed "bitmex" with pip and then I tried to "import bitmex" but here is the message I got from the terminal :

>>> import bitmex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/john/.local/lib/python2.7/site-packages/bitmex.py", line 5, in <module>
    from BitMEXAPIKeyAuthenticator import APIKeyAuthenticator
  File "/home/john/.local/lib/python2.7/site-packages/BitMEXAPIKeyAuthenticator.py", line 1, in <module>
    import urllib.parse
ImportError: No module named parse

If anyone could help.

**Comment by Madward** [comment]
The BitMEX python API is seemingly built for python3. 
In python2, there is no urllib.parse package.

You could switch to Python3, or edit the first line in the BitMEXAPIKeyAuthenticator.py script and hope there is no other line that breaks under Python2.

From:
`import urllib.parse`

To:
`import urlparse`
