### ISSUE TITLE
clieng.User.User_getExecutionHistory()  cause  SwaggerMappingError

### ISSUE THREAD

**Issue by Loches525** [BitMEX/api-connectors#288]
`client = bitmex.bitmex(test=False, api_key="*******************", api_secret="*******************************")`
`result_tra = client.User.User_getExecutionHistory(symbol='XBTUSD', timestamp='2018-12-04T12:00:00.000Z').result()`

`Traceback (most recent call last):
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado_core\formatter.py", line 41, in to_wire
    return formatter.to_wire(value) if formatter else value
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado_core\formatter.py", line 127, in <lambda>
    to_wire=lambda dt: (dt if dt.tzinfo else pytz.utc.localize(dt)).isoformat(),
AttributeError: 'str' object has no attribute 'tzinfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/jarvis/Desktop/BBGData-develop-6c9d2e05b8d6cf8c5c12c19a3526cc5f742c6ecb/test9].py", line 7, in <module>
    result_tra = client.User.User_getExecutionHistory(symbol='XBTUSD', timestamp='2018-12-04T12:00:00.000Z').result()
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\client.py", line 247, in __call__
    self.operation, request_options, **op_kwargs)
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\client.py", line 285, in construct_request
    construct_params(operation, request, op_kwargs)
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\client.py", line 308, in construct_params
    marshal_param(param, param_value, request)
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado_core\param.py", line 121, in marshal_param
    value = marshal_schema_object(swagger_spec, param_spec, value)
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado_core\marshal.py", line 40, in marshal_schema_object
    return marshal_primitive(swagger_spec, schema_object_spec, value)
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado_core\marshal.py", line 87, in marshal_primitive
    value = formatter.to_wire(swagger_spec, primitive_spec, value)
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado_core\formatter.py", line 48, in to_wire
    e,
bravado_core.exception.SwaggerMappingError: ('Error while marshalling value=2018-12-04T12:00:00.000Z to type=string/date-time.', AttributeError("'str' object has no attribute 'tzinfo'",))
`

**Comment by Loches525** [comment]
I try on this link https://www.bitmex.com/api/explorer/#!/User/User_getExecutionHistory, using the same parameter and it works. But it failed when I try these parameters in python. Please kindly advise the reason, thanks!
