### ISSUE TITLE
client.User.User_getExecutionHistory()  casue  SwaggerMappingError

### ISSUE THREAD

**Issue by Loches525** [BitMEX/api-connectors#289]
`import bitmex
import json
import pandas as pd

client = bitmex.bitmex(test=False, api_key="****************", api_secret="******************************")
result_pos = client.Position.Position_get(filter=json.dumps({'symbol': 'XBTUSD'})).result()
t = pd.to_datetime('2018-12-04T12:00:00.000Z')
result_tra = client.User.User_getExecutionHistory(symbol='XBTUSD', timestamp=t).result()`

Traceback (most recent call last):
  File "C:/Users/jarvis/Desktop/BBGData-develop-6c9d2e05b8d6cf8c5c12c19a3526cc5f742c6ecb/test9].py", line 9, in <module>
    result_tra = client.User.User_getExecutionHistory(symbol='XBTUSD', timestamp=t).result()
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 214, in result
    swagger_result = self._get_swagger_result(incoming_response)
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 97, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 239, in _get_swagger_result
    self.request_config.response_callbacks,
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 268, in unmarshal_response
    op=operation,
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado\http_future.py", line 317, in unmarshal_response_inner
    value=content_value,
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado_core\unmarshal.py", line 61, in unmarshal_schema_object
    return unmarshal_object(swagger_spec, schema_object_spec, value)
  File "C:\Users\jarvis\AppData\Local\Programs\Python\Python36\lib\site-packages\bravado_core\unmarshal.py", line 128, in unmarshal_object
    type(object_value), object_value))
bravado_core.exception.SwaggerMappingError: Expected dict like type for <class 'list'>:[....]

**Comment by Loches525** [comment]
Should I need to revise the parameter to a correct format?

**Comment by cryptonaut1357** [comment]
i got the same issue. Any suggestions?

**Comment by Loches525** [comment]
> i got the same issue. Any suggestions?

Actually not yet. Finally there is trades record in the exception info, u can catch them via a python library traceback

**Comment by derekwong9** [comment]
Have the same issue as well, you get records in exception but its really working properly

**Comment by combstraight** [comment]
I get this error as well.

**Comment by combstraight** [comment]
I think the issue is that bitmex REST API returns a list object while unmarshal.unmarshal_object() expects a dictionary list.

**Comment by apojii** [comment]
I get this error as well. Is there any solutions?

**Comment by pierthodo** [comment]
Any update on this ?

**Comment by TobiWo** [comment]
I'm having the same problem here. Very annoying.

**Comment by dcimring** [comment]
I'm having the same issue :(
