### ISSUE TITLE
__on_error() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by simonohanlon101** [BitMEX/api-connectors#311]
```
>>> platform.platform()
'Darwin-18.0.0-x86_64-i386-64bit'
>>> platform.python_version()
'3.7.2'
```

Hi,
I'm trying to get up and running using the Bitmex ws api. I'm having some problems.

I ran exactly the following commands:

```
mkdir -p ~/bitmex && cd ~/bitmex
git clone https://github.com/BitMEX/api-connectors.git
cd api-connectors/official-ws/python
python3 setup.py install
```
I then edited `main.py` to update `api_key` and `api_secret` from `None` to my credentials. Then I ran

```
python3 main.py
```

The response was this:

```
2019-01-17 12:48:12,372 - bitmex_websocket - INFO - Connecting to wss://testnet.bitmex.com/realtime?subscribe=execution:XBTUSD,instrument:XBTUSD,order:XBTUSD,orderBookL2:XBTUSD,position:XBTUSD,quote:XBTUSD,trade:XBTUSD,margin
2019-01-17 12:48:12,372 - bitmex_websocket - INFO - Authenticating with API Key.
2019-01-17 12:48:12,496 - websocket - ERROR - error from callback <bound method BitMEXWebsocket.__on_error of <bitmex_websocket.BitMEXWebsocket object at 0x10ce04278>>: __on_error() takes 2 positional arguments but 3 were given
2019-01-17 12:48:12,508 - websocket - ERROR - error from callback <bound method BitMEXWebsocket.__on_close of <bitmex_websocket.BitMEXWebsocket object at 0x10ce04278>>: __on_close() takes 1 positional argument but 2 were given
```

The console hung for a few minutes until I interrupted it and received this error message:

```
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    run()
  File "main.py", line 12, in run
    api_key='<snipped>', api_secret='<snipped>')
  File "/Users/sohanlon/bitmex/api-connectors/official-ws/python/bitmex_websocket.py", line 49, in __init__
    self.__connect(wsURL, symbol)
  File "/Users/sohanlon/bitmex/api-connectors/official-ws/python/bitmex_websocket.py", line 126, in __connect
    sleep(1)
KeyboardInterrupt
```

What am I missing or doing wrong? Help much appreciated. Please let me know if I have not supplied sufficient information to diagnose the problem.

**Comment by bitRomney** [comment]
Hi, as of now you can't use the web socket API to place or amend orders but you can use it to get public and some private data. For placing/amending orders, I wrote a tutorial here: https://link.medium.com/qDRwB8KgqT. 

For web socket, I got this price logger to fetch a feed of perpetual swap price data for ETHUSD. Can't remember where I got it from, maybe the official-ws. Hopefully you can use this partially to set up a web socket connection.

```
from bitmex_websocket import BitMEXWebsocket
import logging, time

# Basic use of websocket.
def run():
   logger = setup_logger()

   # Instantiating the WS will make it connect. Be sure to add your api_key/api_secret.
   ws = BitMEXWebsocket(endpoint="https://www.bitmex.com/api/v1", symbol="ETHUSD", api_key=“[your_api_key]", api_secret=“[your_api_secret]")

   logger.info("Instrument data: %s" % ws.get_instrument())

   # Run forever
   currentPrice = ws.get_ticker()['last']
   while(ws.ws.sock.connected):
       logger.info("Last Price: %s" % ws.get_instrument()['lastPrice'])
       
       #if ws.api_key:
       #    logger.info("Funds: %s" % ws.funds())
       #logger.info("Market Depth: %s" % ws.market_depth())
       #logger.info("Recent Trades: %s\n\n" % ws.recent_trades())
       sleep(1)

def setup_logger():
   # Prints logger info to terminal
   logger = logging.getLogger()
   logger.setLevel(logging.INFO)  # Change this to DEBUG if you want a lot more info
   ch = logging.StreamHandler()
   # create formatter
   formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
   # add formatter to ch
   ch.setFormatter(formatter)
   logger.addHandler(ch)
   return logger

if __name__ == "__main__":
   run()
```

**Comment by daybyter** [comment]
I opened

~/.local/lib/python3.9/site-packages/websocket/_app.py

went to line 408 and changed the line
====
               callback(self, *args)
====
to:
====
                callback( *args);
====
