### ISSUE TITLE
Cannot set property 'apiKey' of undefined

### ISSUE THREAD

**Issue by Guygeboe** [BitMEX/api-connectors#341]
I'm getting the following error when running the default example. Any suggestions are very welcome, thank you.

> TypeError: Cannot set property 'apiKey' of undefined
>     at Object.<anonymous> (c:\projects\bitmex-order\index.js:12:15)
>     at Module._compile (internal/modules/cjs/loader.js:698:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>     at Module.load (internal/modules/cjs/loader.js:600:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```
var BitMexApi = require('bit_mex_api');
var defaultClient = BitMexApi.ApiClient.instance;

// Configure API key authorization: apiKey
var apiKey = defaultClient.authentications['apiKey'];
apiKey.apiKey = _apiKey;
// Uncomment the following line to set a prefix for the API key, e.g. "Token" (defaults to null)
//apiKey.apiKeyPrefix = 'Token';

// Configure API key authorization: apiNonce
var apiNonce = defaultClient.authentications['apiNonce'];
apiNonce.apiKey = _apiKey;
// Uncomment the following line to set a prefix for the API key, e.g. "Token" (defaults to null)
//apiNonce.apiKeyPrefix = 'Token';

// Configure API key authorization: apiSignature
var apiSignature = defaultClient.authentications['apiSignature'];
apiSignature.apiKey = _apiKey;
// Uncomment the following line to set a prefix for the API key, e.g. "Token" (defaults to null)
//apiSignature.apiKeyPrefix = 'Token';
```

**Comment by biahoi** [comment]
So do I..

**Comment by Guygeboe** [comment]
bump...please halp
