### ISSUE TITLE
Delta Server - Data.map

### ISSUE THREAD

**Issue by ChrisCates** [BitMEX/api-connectors#351]
Should wrap `data` in a condition to prevent this stack trace:

```bash
TypeError: data.map is not a function
    at clone (/home/chris/Crypto/api-connectors/official-ws/delta-server/node_modules/bitmex-realtime-api/index.js:231:15)
    at BitMEXClient.getData (/home/chris/Crypto/api-connectors/official-ws/delta-server/node_modules/bitmex-realtime-api/index.js:98:10)
    at /home/chris/Crypto/api-connectors/official-ws/delta-server/lib/server.js:76:21
    at Layer.handle [as handle_request] (/home/chris/Crypto/api-connectors/official-ws/delta-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/chris/Crypto/api-connectors/official-ws/delta-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/chris/Crypto/api-connectors/official-ws/delta-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/chris/Crypto/api-connectors/official-ws/delta-server/node_modules/express/lib/router/layer.js:95:5)
    at /home/chris/Crypto/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:281:22
    at param (/home/chris/Crypto/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:354:14)
    at param (/home/chris/Crypto/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:365:14)
```

**Comment by mrbreaks** [comment]
same error happen to me.

**Comment by ChrisCates** [comment]
@mrbreaks, I would send in a PR to fix this issue.
But they've ghosted this issue.

**Comment by verata-veritatis** [comment]
Having same issue here.

**Comment by verata-veritatis** [comment]
Check out this response and try editing the function in index.js. I haven’t tried it yet but seems like it worked for this user.

https://github.com/BitMEX/api-connectors/issues/247#issuecomment-516070488

**Comment by ChrisCates** [comment]
@verata-veritatis, there still needs to be a conditional wrap around this source code.
Can be put in a PR.

But again, Bitmex cannot be ghosting an issue before anyone sends a PR in.
