### ISSUE TITLE
TypeError: Cannot read property 'XBTUSD' of undefined

### ISSUE THREAD

**Issue by rick-sanchez-c137** [BitMEX/api-connectors#362]
I have been wooped by this error all day

`BitMEX-Delta-Server listening on http://localhost:4444
WebSocket [INFO]: Connected.
{"op":"subscribe","args":"instrument:XBTUSD"}
{"op":"subscribe","args":"quote:XBTUSD"}
{"op":"subscribe","args":"execution:XBTUSD"}
{"op":"subscribe","args":"margin:*"}
{"op":"subscribe","args":"order:XBTUSD"}
{"op":"subscribe","args":"position:XBTUSD"}
{"op":"subscribe","args":"instrument:ETHUSD"}
{"op":"subscribe","args":"quote:ETHUSD"}
{"op":"subscribe","args":"execution:ETHUSD"}
{"op":"subscribe","args":"order:ETHUSD"}
{"op":"subscribe","args":"position:ETHUSD"}
TypeError: Cannot read property 'XBTUSD' of undefined
    at BitMEXClient.getData (/home/lokke/api-connectors/official-ws/nodejs/index.js:84:32)
    at /home/lokke/api-connectors/official-ws/delta-server/lib/server.js:76:21
    at Layer.handle [as handle_request] (/home/lokke/api-connectors/official-ws/delta-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lokke/api-connectors/official-ws/delta-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/lokke/api-connectors/official-ws/delta-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/lokke/api-connectors/official-ws/delta-server/node_modules/express/lib/router/layer.js:95:5)
    at /home/lokke/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:281:22
    at param (/home/lokke/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:354:14)
    at param (/home/lokke/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/lokke/api-connectors/official-ws/delta-server/node_modules/express/lib/router/index.js:410:3)
`

my config.js
`
// Sample configuration for BitMEX-Delta-Server.
// Copy me to config.js to use custom settings.

module.exports = {
  port: 4444,

  // If false, will connect to live exchange.
  // Testnet is https://testnet.bitmex.com
  testnet: false,

  // Symbols to watch. Add any/all symbols you are going to poll here.
  symbols: ["XBTUSD", "ETHUSD"],

  // Available streams:
  // Public:
  // ["instrument","orderBookL2","quote","trade"]
  // Private:
  // ["execution","margin","order","position"]
  streams: ["instrument","quote","execution","margin","order","position"],

  // If you want to use any of the above "private" streams, you must authenticate with an API Key.
  apiKeyID: '',
  apiKeySecret: '',

  // This prevents memory usage from getting out of control. Tweak to your needs.
  maxTableLen: 50000,
};
`

**Comment by rick-sanchez-c137** [comment]
It works fine if private streams and APIs are taken out.

**Comment by pastet89** [comment]
@rick-sanchez-c137  Did you resolve the issue? I am getting the same error.
