### ISSUE TITLE
Node.js: .getSymbol() is broken, crash

### ISSUE THREAD

**Issue by Bomper** [BitMEX/api-connectors#38]
It's not really clear from the docs how to use [client.getSymbol](https://github.com/BitMEX/api-connectors/blob/master/official-ws/nodejs/README.md#clientgetsymbolstring-symbol) but I guess it should be like this (similar to the [getTable example](https://github.com/BitMEX/api-connectors/pull/37/files) I've figured out and just added):

```js
const client = new BitMEXClient();

client.addStream('XBTUSD', 'trade', () => {});
client.on('error', (e) => console.error('ERROR', e));  // not reached
setTimeout(() => {
  console.log('XBTUSD symbol info during the last few seconds:', client.getSymbol('XBTUSD'));
}, 5000);
```

This crashes though:

```
WebSocket [INFO]: Connected.
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at clone (/bitmex/node_modules/bitmex-realtime-api/index.js:219:15)
    at BitMEXClient.getData (/bitmex/node_modules/bitmex-realtime-api/index.js:85:10)
    at BitMEXClient.getSymbol (/bitmex/node_modules/bitmex-realtime-api/index.js:99:15)
    at Timeout.setTimeout [as _onTimeout] (file:///bitmex/bitmex.js:17:24)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

`client.getData('XBTUSD')` crashes just the same.

I'm using v0.2.3 from npm because of #34.

**Comment by STRML** [comment]
Published `0.2.4` which fixes this.
