### ISSUE TITLE
Python connector: 503 Service Unavailable

### ISSUE THREAD

**Issue by aacoimbra** [BitMEX/api-connectors#385]
My script eventually returns the following error when trying to excecute two orders sequentially:

```
Traceback (most recent call last):                                                                                                                                                                                    File "my_script.py", line 226, in my_function                                                                                                                                                                       client.Order.Order_new(symbol= 'XBTUSD', side='Buy', orderQty= 1000, ordType='Market').result()                                                                                                                     File "/usr/local/lib/python3.5/dist-packages/bravado/http_future.py", line 271, in result                                                                                                                             swagger_result = self._get_swagger_result(incoming_response)                                                                                                                                                      File "/usr/local/lib/python3.5/dist-packages/bravado/http_future.py", line 124, in wrapper                                                                                                                            return func(self, *args, **kwargs)                                                                                                                                                                                File "/usr/local/lib/python3.5/dist-packages/bravado/http_future.py", line 302, in _get_swagger_result                                                                                                                self.request_config.response_callbacks,                                                                                                                                                                           File "/usr/local/lib/python3.5/dist-packages/bravado/http_future.py", line 333, in unmarshal_response                                                                                                                 raise_on_unexpected(incoming_response)                                                                                                                                                                            File "/usr/local/lib/python3.5/dist-packages/bravado/http_future.py", line 407, in raise_on_unexpected                                                                                                                raise make_http_exception(response=http_response)                                                                                                                                                               bravado.exception.HTTPServiceUnavailable: 503 Service Unavailable
--

```

The code to I'm using to execute a sigle order is: `client.Order.Order_new(symbol= 'XBTUSD', side='Buy', orderQty= 1000, ordType='Market').result()`

I quickly found information regarding the [503 error](https://www.bitmex.com/app/restAPI#Overload), but I don't believe it's it because I'm getting it very frequently with the script, although I can't manage to reproduce it by myself (simply sending orders on jupyter).

Any insights?

**Comment by aacoimbra** [comment]
Reply from BitMEX:

> This 503 Service Unavailable error does not seem to be overload. Overload errors are received as: 
> 
> 503 with a JSON payload {"error": {"message": "The system is currently overloaded. Please try again later.", "name": "HTTPError"}}
> 
> I have checked for errors associated with the IP address xxx.xx.xxx.xx over the past 7 days and haven't found any. This suggests the error might be on your end. You will need to examine the implementation of the python client and check for any faults.
