### ISSUE TITLE
Authorization errors when running delta-server against testnet

### ISSUE THREAD

**Issue by bjschnei** [BitMEX/api-connectors#4]
When running: node index.js

With the config.js excluding api_id and api_secret, no errors are seen.
When including and id and secret created on https://testnet.bitmex.com/app/apiKeys

The following errors are seen at startup:

Caught Websocket error: Error: unexpected server response (401)
    at ClientRequest.response (/Users/bjschnei/code/btc_deriv/third_party/api-connectors/official-ws/nodejs/node_modules/ws/lib/WebSocket.js:719:15)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)

Are endpoints not requiring authentication failing if/when it is provided?

**Comment by bjschnei** [comment]
Issue not demonstrated on live exchange endpoint.

**Comment by STRML** [comment]
I'll take a look in the morning; are you certain you're using the correct keys for each env? The testnet and live environments are completely separate; you need to generate an API key for each.

**Comment by bjschnei** [comment]
Yes, I tried with generated keys on each appropriate site.

**Comment by STRML** [comment]
Thanks - the `testnet` option wasn't being propagated properly. That's fixed and I added a few other enhancements as well.
