### ISSUE TITLE
Failed to connect to localhost/0:0:0:0:0:0:0:1:443 using Bitmex Java API

### ISSUE THREAD

**Issue by ken4ward** [BitMEX/api-connectors#411]
This is my first time of trying out BItmex Java API. I ran the example and it resulted in the following error. Please, what's the solution? 

```
Exception when calling AnnouncementApi#announcementGet
io.swagger.client.ApiException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:443
	at io.swagger.client.ApiClient.execute(ApiClient.java:847)
	at io.swagger.client.api.AnnouncementApi.announcementGetWithHttpInfo(AnnouncementApi.java:140)
	at io.swagger.client.api.AnnouncementApi.announcementGet(AnnouncementApi.java:126)
	at io.christdoes.wealth.command.BitmexAPI.run(BitmexAPI.java:21)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at io.christdoes.wealth.CryptoWealthApplication.main(CryptoWealthApplication.java:9)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:443
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.swagger.client.ApiClient.execute(ApiClient.java:843)
	... 9 more
```

**Comment by STRML** [comment]
Fixed in the latest commit. The autogenerated connectors assume `localhost` when no `"host"` is present in the spec. Recommend changing the `basePath` [here](https://github.com/BitMEX/api-connectors/blob/56edbdff0139fa85171dcd8b00b43d434d81c31c/auto-generated/java/src/main/java/io/swagger/client/ApiClient.java#L55) to `testnet.bitmex.com` for testing.

**Comment by ken4ward** [comment]
> Fixed in the latest commit. The autogenerated connectors assume `localhost` when no `"host"` is present in the spec. Recommend changing the `basePath` [here](https://github.com/BitMEX/api-connectors/blob/56edbdff0139fa85171dcd8b00b43d434d81c31c/auto-generated/java/src/main/java/io/swagger/client/ApiClient.java#L55) to `testnet.bitmex.com` for testing.

Thanks. This provided a fix for the problem

**Comment by Nimarrakers** [comment]
> This is my first time of trying out BItmex Java API. I ran the example and it resulted in the following error. Please, what's the solution?
> 
> ```
> Exception when calling AnnouncementApi#announcementGet
> io.swagger.client.ApiException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:443
> 	at io.swagger.client.ApiClient.execute(ApiClient.java:847)
> 	at io.swagger.client.api.AnnouncementApi.announcementGetWithHttpInfo(AnnouncementApi.java:140)
> 	at io.swagger.client.api.AnnouncementApi.announcementGet(AnnouncementApi.java:126)
> 	at io.christdoes.wealth.command.BitmexAPI.run(BitmexAPI.java:21)
> 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
> 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
> 	at io.christdoes.wealth.CryptoWealthApplication.main(CryptoWealthApplication.java:9)
> Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:443
> 	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
> 	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
> 	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
> 	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
> 	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
> 	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
> 	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
> 	at com.squareup.okhttp.Call.getResponse(Call.java:286)
> 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
> 	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
> 	at com.squareup.okhttp.Call.execute(Call.java:80)
> 	at io.swagger.client.ApiClient.execute(ApiClient.java:843)
> 	... 9 more
> ```

**Comment by Nimarrakers** [comment]
> > Fixed in the latest commit. The autogenerated connectors assume `localhost` when no `"host"` is present in the spec. Recommend changing the `basePath` [here](https://github.com/BitMEX/api-connectors/blob/56edbdff0139fa85171dcd8b00b43d434d81c31c/auto-generated/java/src/main/java/io/swagger/client/ApiClient.java#L55) to `testnet.bitmex.com` for testing.
> 
> Thanks. This provided a fix for the problem
