### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'parse'

### ISSUE THREAD

**Issue by sadek69** [BitMEX/api-connectors#439]
OSX 10.15.4
python 3.8.2 

main.py give error :

Traceback (most recent call last):
  File "main.py", line 40, in <module>
    run()
  File "main.py", line 11, in run
    ws = BitMEXWebsocket(endpoint="https://testnet.bitmex.com/api/v1", symbol="XBTUSD",
  File "/Users/_exe/python/bitmex/bitmex_websocket.py", line 47, in __init__
    wsURL = self.__get_url()
  File "/Users/_exe/python/bitmex/bitmex_websocket.py", line 166, in __get_url
    urlParts = list(urllib.parse.urlparse(self.endpoint))
AttributeError: module 'urllib' has no attribute 'parse'

**Comment by STRML** [comment]
Fixed in 3cf93b732354d7722c4a32dcaa8325fef7948d33
