### ISSUE TITLE
Trade_getBucketed:  Signature not valid

### ISSUE THREAD

**Issue by BruceBushby** [BitMEX/api-connectors#472]
Hi 

The following code produces "Signature not valid" 

Example code that produces the error:

#!/usr/bin/env python 

import requests
import bitmex

API_KEY = 'xxxxxxxxxxxx'
API_SECRET = 'xxxxxxxxxxx'

client = bitmex.bitmex(test=False,api_key=API_KEY,api_secret=API_SECRET)
records = client.Trade.Trade_getBucketed(symbol="XBTUSD", binSize="1m", count=2).result()
print(records)

Example output (Signature not valid)

(bitmex) [bruce@bitmex33 collector]$ ./test.py
/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/User/properties/preferences)
  warnings.warn(
Traceback (most recent call last):
  File "/home/bruce/work/penv/bitmex/git/alphax/test-roc/collector/./test.py", line 10, in <module>
    records = client.Trade.Trade_getBucketed(symbol="XBTUSD", binSize="1m", count=2).result()
  File "/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/bravado/http_future.py", line 271, in result
    swagger_result = self._get_swagger_result(incoming_response)
  File "/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/bravado/http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/bravado/http_future.py", line 300, in _get_swagger_result
    unmarshal_response(
  File "/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/bravado/http_future.py", line 353, in unmarshal_response
    raise_on_expected(incoming_response)
  File "/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/bravado/http_future.py", line 420, in raise_on_expected
    raise make_http_exception(
bravado.exception.HTTPUnauthorized: 401 Unauthorized: {'error': {'message': 'Signature not valid.', 'name': 'HTTPError'}}
(bitmex) [bruce@bitmex33 collector]$ 

If I then change "test=True", the response is as expected (Invalid API Key)

(bitmex) [bruce@bitmex33 collector]$ cat test.py
#!/usr/bin/env python 

import requests
import bitmex

API_KEY = 'xxxxxxxxxxxxx'
API_SECRET = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

client = bitmex.bitmex(test=True,api_key=API_KEY,api_secret=API_SECRET)
records = client.Trade.Trade_getBucketed(symbol="XBTUSD", binSize="1m", count=2).result()
print(records)

(bitmex) [bruce@bitmex33 collector]$ ./test.py
/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/User/properties/preferences)
  warnings.warn(
Traceback (most recent call last):
  File "/home/bruce/work/penv/bitmex/git/alphax/test-roc/collector/./test.py", line 10, in <module>
    records = client.Trade.Trade_getBucketed(symbol="XBTUSD", binSize="1m", count=2).result()
  File "/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/bravado/http_future.py", line 271, in result
    swagger_result = self._get_swagger_result(incoming_response)
  File "/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/bravado/http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/bravado/http_future.py", line 300, in _get_swagger_result
    unmarshal_response(
  File "/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/bravado/http_future.py", line 353, in unmarshal_response
    raise_on_expected(incoming_response)
  File "/home/bruce/work/penv/bitmex/lib/python3.9/site-packages/bravado/http_future.py", line 420, in raise_on_expected
    raise make_http_exception(
bravado.exception.HTTPUnauthorized: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}
(bitmex) [bruce@bitmex33 collector]$ 

So my API keys are correct (triple checked)

The above code was definitely working on the 29th March 2020.

My initial machine that was working in March 2020 was "Fedora 28" 

I have rebuilt a new machine based on "Fedora 33" which produces the same error. 

Any help would be much appreciated. 

Thanks
Bruce

**Comment by BruceBushby** [comment]
List of packages installed via "pip"

(bitmex) [bruce@bitmex33 collector]$ pip list
Package                Version
---------------------- ---------
asyncpg                0.21.0
attrs                  20.3.0
bitmex                 0.2.2
bravado                11.0.2
bravado-core           5.17.0
certifi                2020.12.5
chardet                4.0.0
idna                   2.10
jsonpointer            2.0
jsonref                0.2
jsonschema             3.2.0
monotonic              1.5
msgpack                1.0.2
newtulipy              0.4.2
numpy                  1.19.5
pandas                 1.2.0
pip                    20.3.3
pyrsistent             0.17.3
python-dateutil        2.8.1
pytz                   2020.5
PyYAML                 5.3.1
requests               2.25.1
rfc3987                1.3.8
setuptools             49.1.3
simplejson             3.17.2
six                    1.15.0
strict-rfc3339         0.7
swagger-spec-validator 2.7.3
TA-Lib                 0.4.19
tqdm                   4.56.0
typing-extensions      3.7.4.3
urllib3                1.26.2
webcolors              1.11.1
wheel                  0.34.2
(bitmex) [bruce@bitmex33 collector]$

**Comment by BruceBushby** [comment]
Solved.

Turns out, my account was disabled for API access because I had not completed verification.

The key existed before the account was disabled which resulted in the "Signature not valid"  error message. 

After deleting all keys are re-creating, the error changed to: 
"Your account has been disabled from using the API. Please contact support."


And finally, after verification, all working as expected.
