### ISSUE TITLE
KeyError due to improper handling of action in bitmex_websocket. 

### ISSUE THREAD

**Issue by level29access** [BitMEX/api-connectors#72]
https://github.com/BitMEX/api-connectors/blob/01aecc4a16586cab0ec46980990824deeed2a61b/official-ws/python/bitmex_websocket.py#L215
https://github.com/BitMEX/api-connectors/blob/01aecc4a16586cab0ec46980990824deeed2a61b/official-ws/python/bitmex_websocket.py#L226

This issue arises during startup of Websocket client.

    item = findItemByKeys(self.keys[table], self.data[table], updateData)
KeyError: u'orderBookL2'

    item = findItemByKeys(self.keys[table], self.data[table], deleteData)
KeyError: u'orderBookL2'
'

**Cause:** It is causing because keys table is not populate for that table  (cases when update action is received before  partial.)

**How to resolve it?**: We can ignore the actions update and delete before partial, one way is to lookup if keys are present for that table if not skip it else perform that action.

Example: 

    if table not in self.keys:

      break

**Comment by ryanfox** [comment]
I'm not able to reproduce this - what steps do you follow to encounter it?

**Comment by level29access** [comment]
You can reproduce it if you run the python websocket for prod end point:wss://www.bitmex.com/realtime
This occur due to update event received before partial one.

Try to run python websocket multiple times to get update before partial action and boom you will get the error.

**Comment by level29access** [comment]
Stack trace during one of run:
bravo@alpha:~/git_clone/20180126_v001/api-connectors/official-ws/python$ python main.py 
2018-01-26 15:03:03,964 - bitmex_websocket - INFO - Connecting to wss://www.bitmex.com/realtime?subscribe=execution:XBTUSD,instrument:XBTUSD,order:XBTUSD,orderBookL2:XBTUSD,position:XBTUSD,quote:XBTUSD,trade:XBTUSD,margin
2018-01-26 15:03:03,964 - bitmex_websocket - INFO - Not authenticating.
2018-01-26 15:03:04,897 - bitmex_websocket - ERROR - Traceback (most recent call last):
  File "/home/bravo/git_clone/20180126_v001/api-connectors/official-ws/python/bitmex_websocket.py", line 215, in __on_message
    item = findItemByKeys(self.keys[table], self.data[table], updateData)
KeyError: u'instrument'

2018-01-26 15:03:04,898 - bitmex_websocket - ERROR - Traceback (most recent call last):
  File "/home/bravo/git_clone/20180126_v001/api-connectors/official-ws/python/bitmex_websocket.py", line 215, in __on_message
    item = findItemByKeys(self.keys[table], self.data[table], updateData)
KeyError: u'orderBookL2'

2018-01-26 15:03:04,898 - bitmex_websocket - ERROR - Traceback (most recent call last):
  File "/home/bravo/git_clone/20180126_v001/api-connectors/official-ws/python/bitmex_websocket.py", line 215, in __on_message
    item = findItemByKeys(self.keys[table], self.data[table], updateData)
KeyError: u'orderBookL2'

2018-01-26 15:03:04,899 - bitmex_websocket - ERROR - Traceback (most recent call last):
  File "/home/bravo/git_clone/20180126_v001/api-connectors/official-ws/python/bitmex_websocket.py", line 215, in __on_message
    item = findItemByKeys(self.keys[table], self.data[table], updateData)
KeyError: u'orderBookL2'

2018-01-26 15:03:04,913 - bitmex_websocket - ERROR - Traceback (most recent call last):
  File "/home/bravo/git_clone/20180126_v001/api-connectors/official-ws/python/bitmex_websocket.py", line 215, in __on_message
    item = findItemByKeys(self.keys[table], self.data[table], updateData)
KeyError: u'instrument'

2018-01-26 15:03:04,950 - bitmex_websocket - ERROR - Traceback (most recent call last):
  File "/home/bravo/git_clone/20180126_v001/api-connectors/official-ws/python/bitmex_websocket.py", line 215, in __on_message
    item = findItemByKeys(self.keys[table], self.data[table], updateData)
KeyError: u'orderBookL2'

2018-01-26 15:03:04,951 - bitmex_websocket - ERROR - Traceback (most recent call last):
  File "/home/bravo/git_clone/20180126_v001/api-connectors/official-ws/python/bitmex_websocket.py", line 215, in __on_message
    item = findItemByKeys(self.keys[table], self.data[table], updateData)
KeyError: u'orderBookL2'

2018-01-26 15:03:04,961 - bitmex_websocket - ERROR - Traceback (most recent call last):
  File "/home/bravo/git_clone/20180126_v001/api-connectors/official-ws/python/bitmex_websocket.py", line 215, in __on_message
    item = findItemByKeys(self.keys[table], self.data[table], updateData)
KeyError: u'orderBookL2'

2018-01-26 15:03:04,966 - bitmex_websocket - ERROR - Traceback (most recent call last):
  File "/home/bravo/git_clone/20180126_v001/api-connectors/official-ws/python/bitmex_websocket.py", line 215, in __on_message
    item = findItemByKeys(self.keys[table], self.data[table], updateData)
KeyError: u'orderBookL2'

2018-01-26 15:03:04,966 - bitmex_websocket - INFO - Connected to WS.
2018-01-26 15:03:04,967 - bitmex_websocket - INFO - Got all market data. Starting.
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    run()
  File "main.py", line 14, in run
    logger.info("Instrument data: %s" % ws.get_instrument())
  File "/home/bravo/git_clone/20180126_v001/api-connectors/official-ws/python/bitmex_websocket.py", line 60, in get_instrument
    instrument = self.data['instrument'][0]
IndexError: list index out of range
bravo@alpha:~/git_clone/20180126_v001/api-connectors/official-ws/python$

**Comment by ryanfox** [comment]
One way to prevent these is specifying an API key and secret. `BitMEXWebsocket.__wait_for_account()` prevents accessing that value before `orderBookL2` has been received.

I'm investigating a way to prevent these in the unauthenticated case as well.

**Comment by pigslayer12** [comment]
@ryanfox unfortunately I still get the error despite providing my keys. Sometimes it happens and sometimes it doesnt. Do you know why, or another work around?

**Comment by scoupafi** [comment]
I'm having the same issue almost everytime I try to connect.
It means that for some tries, at first, the server returns an incorrect response.

**Comment by ryanfox** [comment]
Are you logging the messages that are received by the client? It would be instructive to see the actual messages received in order.

**Comment by OleksiyF** [comment]
I've solved the problem by making the modification.

![bitmexwait](https://user-images.githubusercontent.com/38247546/38552866-c8cfdf80-3cbd-11e8-8ffc-c7ca1b108cf2.png)
