### ISSUE TITLE
Bitmex Delta Server - Missing item Warnings

### ISSUE THREAD

**Issue by AlexB1337** [BitMEX/api-connectors#74]
Hi all,
after launching the Delta Server (node) I start receiving warnings, see below:

```
Caught Websocket error: Error: Update for missing item came through on XBTUSD. Data: {"symbol":"XBTUSD","id":15598896150,"side":"Buy","size":108901}
    at updateStore (/home/alex/bit/api-connectors/official-ws/nodejs/lib/deltaParser.js:135:13)
    at Object._update (/home/alex/bit/api-connectors/official-ws/nodejs/lib/deltaParser.js:77:24)
    at Object.onAction (/home/alex/bit/api-connectors/official-ws/nodejs/lib/deltaParser.js:50:40)
    at BitMEXClient.<anonymous> (/home/alex/bit/api-connectors/official-ws/nodejs/index.js:214:37)
    at BitMEXClient.EventEmitter.emit (/home/alex/bit/api-connectors/official-ws/nodejs/node_modules/eventemitter2/lib/eventemitter2.js:382:22)
    at Object.keys.forEach (/home/alex/bit/api-connectors/official-ws/nodejs/lib/createSocket.js:98:13)
    at Array.forEach (<anonymous>)
    at emitSplitData (/home/alex/bit/api-connectors/official-ws/nodejs/lib/createSocket.js:95:27)
    at WebSocketClient.wsClient.onmessage (/home/alex/bit/api-connectors/official-ws/nodejs/lib/createSocket.js:56:7)
    at WebSocket.instance.on (/home/alex/bit/api-connectors/official-ws/nodejs/lib/ReconnectingSocket.js:24:14)
```

Is it something I have to fix before setting my trading robot in production? (i.e. will it cause server fail?)

Thanks,
Alex.

**Comment by ryanfox** [comment]
That error occurs when the client receives an update before the full data set. Are you able to reliably reproduce the error?

**Comment by barl0g** [comment]
Sometimes I get this error too. How do I make this program terminates when this error occurs? This is necessary for the program restarts.
