### ISSUE TITLE
WebSocket [ERROR]: WebSocket closed with code 1006

### ISSUE THREAD

**Issue by SamSlate** [BitMEX/api-connectors#76]
https://github.com/BitMEX/api-connectors/tree/master/official-ws/nodejs

```
WebSocket [ERROR]: WebSocket closed with code 1006
  BitMEX:realtime-api:socket Connection to BitMEX at wss://testnet.bitmex.com/realtime?api-nonce=1517028049451&api-key=egA_GDa1ibphikXh8v9Z3C6&api-signature=89addd4e34c2149ea50588be07cdf6b1f45060bc089866d8fe63a83c1f689cc closed. +60s
Connection closed.
WebSocket [INFO]: Retry in 1000 ms
WebSocket [INFO]: Reconnecting...
  BitMEX:realtime-api:socket:internal open() +1m
WebSocket [ERROR]: Unexpected response from server [400]: {"error":"Nonce is not increasing. This nonce: 1517028049451, last nonce: 1517028049451"}
WebSocket [INFO]: The WebSocket will terminate. Please manually reconnect.
WebSocket [ERROR]: WebSocket closed unexpectedly.
  BitMEX:realtime-api:socket Connection to BitMEX at wss://testnet.bitmex.com/realtime?api-nonce=1517028049451&api-key=egA_GDa1ibphikXh8v9Z3C6&api-signature=89addd4e34c2149ea50588be07cdf6b1f45060bc089866d8fe63a83c1f689cc closed. +2s
Connection closed.
C:\Users\XXXXXX\OneDrive\Documents\Work\crypto\bitmex-api-nodejs\lib\createSocket.js:70
    if (!listeners.length) throw new Error('WebSocket closed. Please check errors above.');
                           ^

Error: WebSocket closed. Please check errors above.
    at WebSocketClient.wsClient.onend (C:\Users\XXXXXX\OneDrive\Documents\Work\crypto\bitmex-api-nodejs\lib\createSocket.js:70:34)
    at WebSocket.instance.on (C:\Users\XXXXXX\OneDrive\Documents\Work\crypto\bitmex-api-nodejs\lib\ReconnectingSocket.js:46:18)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at closeConnection (C:\Users\XXXXXX\OneDrive\Documents\Work\crypto\bitmex-api-nodejs\lib\ReconnectingSocket.js:73:30)
    at IncomingMessage.response.on (C:\Users\XXXXXX\OneDrive\Documents\Work\crypto\bitmex-api-nodejs\lib\ReconnectingSocket.js:86:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)

C:\Users\XXXXXX\OneDrive\Documents\Work\crypto\bitmex-api-nodejs>
```

Websockets fails with code 1006. 

`function makeEndpoint(options)` ([line 110](https://github.com/BitMEX/api-connectors/blob/01aecc4a16586cab0ec46980990824deeed2a61b/official-ws/nodejs/lib/createSocket.js#L110) is never called by reconnect functions so nonce is not updated and the reconnect also fails. 

* There is a problem that causes error 1006 which i cannot identify
* reconnects fail because nonce is not updated.

**Comment by SamSlate** [comment]
https://github.com/BitMEX/api-connectors/pull/71

^this pull fixes the reconnect issue and should be merged. 

The 1006 error persists.

**Comment by ryanfox** [comment]
Code `1006` indicates the connection was closed improperly, e.g. a proxy that does not correctly support websockets. Are you using a proxy?

**Comment by Ahmed-Abdelhak** [comment]
> Code `1006` indicates the connection was closed improperly, e.g. a proxy that does not correctly support websockets. Are you using a proxy?

what if I use INGRESS on the google cloud ( as an API Gateway )
